import {
  Apple,
  Beer,
  Book,
  Cake,
  Candy,
  Coffee,
  Cookie,
  Gem,
  Gift,
  IceCreamCone,
  Pill,
  Pizza,
  Popcorn,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Tag,
  Utensils,
  Wine,
  type LucideIcon,
} from 'lucide-react'

const categoryIcons: Record<string, LucideIcon> = {
  gift: Gift,
  tag: Tag,
  coffee: Coffee,
  shirt: Shirt,
  book: Book,
  cake: Cake,
  candy: Candy,
  cookie: Cookie,
  pizza: Pizza,
  popcorn: Popcorn,
  apple: Apple,
  beer: Beer,
  wine: Wine,
  'ice-cream': IceCreamCone,
  'ice-cream-cone': IceCreamCone,
  pill: Pill,
  gem: Gem,
  phone: Smartphone,
  smartphone: Smartphone,
  sofa: Sofa,
  furniture: Sofa,
  bag: ShoppingBag,
  'shopping-bag': ShoppingBag,
  food: Utensils,
  utensils: Utensils,
}

// falls back to a generic tag icon when a category has no matching icon
export const getCategoryIcon = (icon?: string | null): LucideIcon =>
  categoryIcons[icon?.toLowerCase().trim() ?? ''] ?? Tag
